number_unit:
  零: 0
  一: 1
  壹: 1
  幺: 1
  二: 2
  贰: 2
  两: 2
  三: 3
  叁: 3
  四: 4
  肆: 4
  五: 5
  伍: 5
  六: 6
  陆: 6
  七: 7
  柒: 7
  八: 8
  捌: 8
  九: 9
  玖: 9
  十: 10
  拾: 10
  百: 100
  佰: 100
  千: 1000
  仟: 1000
  万: 10000
  亿: 100000000

number_low: 
  - 零
  - 一
  - 二
  - 三
  - 四
  - 五
  - 六
  - 七
  - 八
  - 九

number_up:
  - 零
  - 壹
  - 贰
  - 叁
  - 肆
  - 伍
  - 陆
  - 柒
  - 捌
  - 玖


unit_low:
  - ""
  - 十
  - 百
  - 千
  - 万
  - 十
  - 百
  - 千
  - 亿
  - 十
  - 百
  - 千
  - 万
  - 十
  - 百
  - 千

unit_up:
  - ""
  - 拾
  - 佰
  - 仟
  - 万
  - 拾
  - 佰
  - 仟
  - 亿
  - 拾
  - 佰
  - 仟
  - 万
  - 拾
  - 佰
  - 仟
